// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfmD2rD_-D7-i-BzEQEhQq_h58ps-hv_U',
    appId: '1:786759238479:web:dbbb2ee1e832336b11fb3a',
    messagingSenderId: '786759238479',
    projectId: 'chart-5717b',
    authDomain: 'chart-5717b.firebaseapp.com',
    storageBucket: 'chart-5717b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_--j70_zCfj5kHCODfOfgMfh3ynrPJI8',
    appId: '1:786759238479:android:74c01393cf57f7a511fb3a',
    messagingSenderId: '786759238479',
    projectId: 'chart-5717b',
    storageBucket: 'chart-5717b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYPepSgGo-2tf2W-VfvVfAgYi1X94wh0g',
    appId: '1:786759238479:ios:f6cde4d32141501611fb3a',
    messagingSenderId: '786759238479',
    projectId: 'chart-5717b',
    storageBucket: 'chart-5717b.appspot.com',
    iosClientId:
        '786759238479-heb9dmn063cenuflkhlgqpldq7it6qu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYPepSgGo-2tf2W-VfvVfAgYi1X94wh0g',
    appId: '1:786759238479:ios:f6cde4d32141501611fb3a',
    messagingSenderId: '786759238479',
    projectId: 'chart-5717b',
    storageBucket: 'chart-5717b.appspot.com',
    iosClientId:
        '786759238479-heb9dmn063cenuflkhlgqpldq7it6qu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishFarm',
  );

  
}
